### ISSUE TITLE
webpack 应该怎么配置？

### ISSUE THREAD

**Issue by 18706789739** [woodensail/css-theme#1]

**Comment by woodensail** [comment]
目前没有支持直接webpack调用，以支持模式包括gulp直接调用，less插件调用和postcss插件调用。

如果没有使用gulp，可以考虑以less插件或postcss插件的形式调用

**Comment by 18706789739** [comment]
您less插件模式中，只提供了gulp代码demo，是否可以提供webpack 插件模式的demo代码？

**Comment by 18706789739** [comment]
require('css-theme').less
我在webpack中这样导入 ，是undefined

**Comment by woodensail** [comment]
你能提供一下你的less配置吗，less插件本身是不依赖于gulp或webpack的

**Comment by 18706789739** [comment]
loaders: [
      {
        test: /\.less$/,
        loaders: ['style', 'css','less'],
        plugins:[new LessPluginTheme(themeConfig)]
      }
    ],

**Comment by 18706789739** [comment]
打包时错误：LessPluginTheme is not a constructor；
console发现require的包是undefined  去掉.less是可以获取到包的

**Comment by woodensail** [comment]
嗯，我后来改了引入方式，似乎忘了改demo？

**Comment by 18706789739** [comment]
给你小星星了大神 ，麻烦快改改demo

**Comment by woodensail** [comment]
不对，改过了啊。
```
var gulp = require('gulp');
var less = require('gulp-less');
// 为了照顾postcss的特殊插件模式，改为直接引入main文件
var LessPluginTheme = require('css-theme');
var themeConfig = require('./theme.config');
console.log(new LessPluginTheme({less: true, ...themeConfig}))

gulp.task('default', function () {
  return gulp.src('./index.less')
    .pipe(less({
     // 在配置项中指定less:true，从而指定以less组件模式初始化
      plugins: [new LessPluginTheme({less: true, ...themeConfig})]
    }))
    .pipe(gulp.dest('./dist'));
});
```

**Comment by 18706789739** [comment]
编译失败：color: #theme1; 貌似是这个值替换出了问题，是plugins 没有起作用吗

**Comment by woodensail** [comment]
嗯，你是直接写的color:#theme1 还是定义了变量？直接写是会报错的。

**Comment by woodensail** [comment]
如果报错一直解决不掉可以考虑使用合法而不经常使用的颜色作为占位符比如#fffffe
