### ISSUE TITLE
这个替换是在less编译前还是编译后？

### ISSUE THREAD

**Issue by 18706789739** [woodensail/css-theme#3]
被替换的变量，使用例如darken之类的less函数会报错

**Comment by 18706789739** [comment]
我看目前是addPostProcessor后处理器，可以改成addPreProcessor预处理器吗？我想应该就可以使用less函数了，但是会报错

**Comment by woodensail** [comment]
目前暂时没空对这个进行修改了，你可以考虑fork后自行修改
